{{- range $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "default" }}
spec:
  type: ClusterIP
  ports:
    {{- range .service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default (printf "%s-%v" $service.name .port )}}
    {{- end }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "default" }}
subsets:
  - addresses:
      {{- range .endpoint.addresses }}
      - ip: {{ . }}
      {{- end }}
    ports:
      {{- range .endpoint.ports }}
      - port: {{ .port }}
        name: {{ .name | default (printf "%s-%v" $service.name .port )}}
      {{- end }}
{{- if and .ingress.enabled .ingress.host }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "default" }}
  annotations:
    {{- if .ingress.annotations }}
    {{- toYaml .ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .ingress.className }}
  ingressClassName: {{ .ingress.className }}
  {{- end }}
  rules:
    - host: {{ .ingress.host }}
      http:
        paths:
        {{- if .ingress.paths }}
        {{- range .ingress.paths }}
        - path: {{ .path }}
          pathType: {{ .pathType | default "Prefix" }}
          backend:
            service:
              name: {{ $service.name }}
              port:
                number: {{ .port }}
          {{- end }}
        {{- else }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $service.name }}
              port:
                number: {{ (index .service.ports 0).port }}
        {{- end }}
  {{- if .ingress.tls }}
  tls:
    - hosts:
        - {{ .ingress.host }}
      secretName: {{ .name }}-tls
  {{- end }}
{{- end }}
{{- end }}
