{{ if .Values.ingress.enabled }}
{{ if .Values.ingress.clusterIssuer }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cvat-ingress
spec:
  secretName: cvat-ingress
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.host }}
  dnsNames:
  - {{ .Values.ingress.host }}
---
{{ end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cvat-ingress
  annotations:
{{- if semverCompare "<1.21-0" .Capabilities.KubeVersion.GitVersion }}
      kubernetes.io/ingress.class: {{ .Values.ingress.ingressClassName }}
{{- end }}
      nginx.ingress.kubernetes.io/proxy-body-size: 900m
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "*"
      nginx.ingress.kubernetes.io/cors-allow-headers: X-XSRF-TOKEN,Accept,Accept-Encoding,Accept-Language,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Origin,Connection,Content-Length,Content-Type,Host,Referer,User-Agent
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/use-regex: "true"
{{- if eq .Values.ingress.ingressClassName "alb"}}      
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
        { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      {{- if .Values.ingress.certificateArn }}  
      alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
      {{- end }}
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/success-codes: 200-399
      alb.ingress.kubernetes.io/target-type: ip
      {{-  if eq (.Values.ingress.cognitoEnabled | toString) "true" }}
      alb.ingress.kubernetes.io/auth-type: cognito
      alb.ingress.kubernetes.io/auth-scope: openid
      alb.ingress.kubernetes.io/auth-session-timeout: '3600'
      alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
      alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
      alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "{{ .Values.ingress.cognitoUserPool }}","UserPoolClientId":"{{ .Values.ingress.cognitoUserPoolClient }}","UserPoolDomain":"{{ .Values.ingress.cognitoUserPoolDomain }}"}'
      {{- end}}
{{- end }}
spec:
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ingress.clusterIssuer }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: cvat-ingress
{{- end }}
  rules:
  - http:
{{- if eq .Values.ingress.ingressClassName "nginx" }}
        paths:
          - path: "/(api|git|opencv|analytics|static|documentation|django-rq|admin)(.*)"
            pathType: ImplementationSpecific
            backend:
                service: 
                    name: cvat
                    port:
                        number: 8080
          - path: "/.*"
            pathType: ImplementationSpecific
            backend:
                service: 
                    name: cvat-ui
                    port:
                        number: 80
{{ else if eq .Values.ingress.ingressClassName "alb" }}
        paths:
        - backend:
            service:
              name: cvat
              port:
                number: 8080
          path: /api
          pathType: Prefix
        - backend:
            service:
              name: cvat
              port:
                number: 8080
          path: /opencv
          pathType: Prefix
        - backend:
            service:
              name: cvat
              port:
                number: 8080
          path: /analytics
          pathType: Prefix
        - backend:
            service:
              name: cvat
              port:
                number: 8080
          path: /static
          pathType: Prefix
        - backend:
            service:
              name: cvat
              port:
                number: 8080
          path: /documentation
          pathType: Prefix
        - backend:
            service:
              name: cvat
              port:
                number: 8080
          path: /django-rq
          pathType: Prefix
        - backend:
            service:
              name: cvat
              port:
                number: 8080
          path: /admin
          pathType: Prefix
        - backend:
            service:
              name: cvat-ui
              port:
                number: 80
          path: /
          pathType: Prefix
{{- end }}          
{{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
{{- end }}

#    proxy_pass_header       X-CSRFToken;
#    proxy_set_header        Host $http_host;
#    proxy_pass_header       Set-Cookie;
{{ end }}