name: Check CODEOWNERS

on: workflow_call

permissions:
  contents: read

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: arc-runners-helm-charts
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
      - name: Install yq
        run: |
          GOBIN="${RUNNER_TEMP}/bin" go install github.com/mikefarah/yq/v4@v4.45.1
          echo "${RUNNER_TEMP}/bin" >> "${GITHUB_PATH}"
      - name: generate CODEOWNERS
        run: |
          ./scripts/check-codeowners.sh > .github/CODEOWNERS
      - name: check CODEOWNERS for modifications
        run: |
          git diff --exit-code || echo "::warning::There is at least one codeowner mismatch."
